spring:
  cloud:
    gateway:
      routes:
        - id: corebanking-auth
          uri: http://localhost:${corebanking.mock.port}
          predicates:
            - Path=/api/auth/**

        - id: corebanking-customer
          uri: http://localhost:${corebanking.mock.port}
          predicates:
            - Path=/api/customers/**

        - id: corebanking-account
          uri: http://localhost:${corebanking.mock.port}
          predicates:
            - Path=/api/accounts/**

        - id: corebanking-transaction
          uri: http://localhost:${corebanking.mock.port}
          predicates:
            - Path=/api/transactions/**

        - id: corebanking-ledger
          uri: http://localhost:${corebanking.mock.port}
          predicates:
            - Path=/api/ledger/**

        - id: audit-service
          uri: http://localhost:${audit.mock.port}
          predicates:
            - Path=/api/audit/**

        - id: reporting-service
          uri: http://localhost:${audit.mock.port}
          predicates:
            - Path=/api/reports/**

eureka:
  client:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG