apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gate
  namespace: banking-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gate
  template:
    metadata:
      labels:
        app: api-gate
    spec:
      containers:
        - name: api-gate
          image: banking-platform/api-gate:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9080
          envFrom:
            - configMapRef:
                name: banking-platform-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gate
  namespace: banking-platform
spec:
  selector:
    app: api-gate
  ports:
    - port: 9080
      targetPort: 9080
  type: NodePort       #  NodePort so you can access it from your browser