apiVersion: v1
kind: Secret
metadata:
  name: banking-platform-secrets
  namespace: banking-platform
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://<your-local-or-remote-db>:5432/corebanking_db"
  DB_USERNAME: "your_username"
  DB_PASSWORD: "your_password"
  JWT_SECRET: "v2DQ/qdsoALW2JjL8a86ENcoBIE1QWAm2sIn10LJa1U="